#!/bin/busybox sh

# Copyright Cartesi and individual authors (see AUTHORS)
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

export IPFS_PATH=/root/.ipfs
export HTTP_DATASTORE_URL=http://127.0.0.1:5005/ipfs
/usr/bin/ipfs init /etc/ipfs-config
/usr/bin/ipfs daemon --offline &
echo "Waiting for IPFS"
IPFS_HOST="127.0.0.1"
IPFS_PORT="5001"

while true; do
	nc "$IPFS_HOST" "$IPFS_PORT" < /dev/null
        RET=$?
        echo $RET
        if [ x$RET = x0 ]; then
           break
        fi
        sleep 1
done
echo "IPFS up"

/usr/bin/lambada-http-server $*