name: Build
on: [push]
env:
  TOOLCHAIN_IMAGE: cartesi/toolchain
  TOOLCHAIN_TAG: 0.15.0
jobs:
  tools:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Export makefile variables
        run: make env >> $GITHUB_ENV

      - name: Download and check dependencies
        run: make checksum

      - name: Buildx setup
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: zippiehq/lambada-guest-tools
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build [${{ env.MACHINE_EMULATOR_TOOLS_TAR_GZ }}]
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          push: false
          load: true
          build-args: |
            MACHINE_EMULATOR_TOOLS_TAR_GZ=${{ env.MACHINE_EMULATOR_TOOLS_TAR_GZ }}
            MACHINE_EMULATOR_TOOLS_DEB=${{ env.MACHINE_EMULATOR_TOOLS_DEB }}
            MACHINE_EMULATOR_TOOLS_VERSION=${{ env.MACHINE_EMULATOR_TOOLS_VERSION }}
            LINUX_SOURCES_VERSION=${{ env.LINUX_SOURCES_VERSION }}
            LINUX_SOURCES_FILEPATH=${{ env.LINUX_SOURCES_FILEPATH }}
            RNDADDENTROPY_VERSION=${{ env.RNDADDENTROPY_VERSION }}
            RNDADDENTROPY_FILEPATH=${{ env.RNDADDENTROPY_FILEPATH }}
          cache-from: type=gha,scope=regular,mode=max
          cache-to: type=gha,scope=regular

      - name: Retrieve artifacts
        run: make copy MACHINE_EMULATOR_TOOLS_IMAGE=`echo "${{ steps.docker_meta.outputs.tags }}" | head -1 | cut -d "," -f 1 | xargs`

      - name: Upload [${{ env.MACHINE_EMULATOR_TOOLS_TAR_GZ }}]
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.MACHINE_EMULATOR_TOOLS_TAR_GZ }}
          path: ${{ env.MACHINE_EMULATOR_TOOLS_TAR_GZ }}

      - name: Upload [${{ env.MACHINE_EMULATOR_TOOLS_DEB }}]
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.MACHINE_EMULATOR_TOOLS_DEB }}
          path: ${{ env.MACHINE_EMULATOR_TOOLS_DEB }}

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          prerelease: true
          files: |
            ${{ env.MACHINE_EMULATOR_TOOLS_TAR_GZ }}
            ${{ env.MACHINE_EMULATOR_TOOLS_DEB }}
